// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'inference/tensor.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `emit_aggregated_result`, `emit_model_manifest`, `emit_token`, `get_inference_engine`, `get_peer_state`

Future<bool> loadModel({required String path}) =>
    RustLib.instance.api.crateApiLoadModel(path: path);

Future<bool> loadTokenizer({required String path}) =>
    RustLib.instance.api.crateApiLoadTokenizer(path: path);

Stream<Float32List> aggregatedResultStream() =>
    RustLib.instance.api.crateApiAggregatedResultStream();

Future<void> startMeshNode({required int port}) =>
    RustLib.instance.api.crateApiStartMeshNode(port: port);

Stream<String> peerDiscoveryStream() =>
    RustLib.instance.api.crateApiPeerDiscoveryStream();

Stream<String> modelManifestStream() =>
    RustLib.instance.api.crateApiModelManifestStream();

Stream<String> tokenStream() => RustLib.instance.api.crateApiTokenStream();

Future<String> executeInference({required String prompt}) =>
    RustLib.instance.api.crateApiExecuteInference(prompt: prompt);

Future<bool> startNode(
        {required String listenAddr,
        required String nextPeerAddr,
        required int ringSize,
        required String nodeId}) =>
    RustLib.instance.api.crateApiStartNode(
        listenAddr: listenAddr,
        nextPeerAddr: nextPeerAddr,
        ringSize: ringSize,
        nodeId: nodeId);

Future<bool> connectToPeer({required String peerAddr}) =>
    RustLib.instance.api.crateApiConnectToPeer(peerAddr: peerAddr);

Future<String> sendPrompt(
        {required String originatorId,
        required String prompt,
        required String nextPeerAddr}) =>
    RustLib.instance.api.crateApiSendPrompt(
        originatorId: originatorId, prompt: prompt, nextPeerAddr: nextPeerAddr);

Future<void> triggerModelDistribution({required String modelId}) =>
    RustLib.instance.api.crateApiTriggerModelDistribution(modelId: modelId);

Future<String> getTelemetryJson() =>
    RustLib.instance.api.crateApiGetTelemetryJson();

Future<String> getDiscoveredPeersHealth() =>
    RustLib.instance.api.crateApiGetDiscoveredPeersHealth();

Future<SharedTensorBuffer> allocateSharedBuffer({required BigInt size}) =>
    RustLib.instance.api.crateApiAllocateSharedBuffer(size: size);

Future<void> freeSharedBuffer({required SharedTensorBuffer buf}) =>
    RustLib.instance.api.crateApiFreeSharedBuffer(buf: buf);

Future<void> processTensorZeroCopy(
        {required BigInt ptr, required BigInt len}) =>
    RustLib.instance.api.crateApiProcessTensorZeroCopy(ptr: ptr, len: len);

Future<void> notifyGracefulLeave() =>
    RustLib.instance.api.crateApiNotifyGracefulLeave();

Future<void> updateNodeThrottling({required bool lowPowerMode}) =>
    RustLib.instance.api
        .crateApiUpdateNodeThrottling(lowPowerMode: lowPowerMode);
