// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// A C-compatible shared memory buffer for zero-copy tensor pass-through.
class SharedTensorBuffer {
  final BigInt ptr;
  final BigInt len;
  final BigInt capacity;

  const SharedTensorBuffer({
    required this.ptr,
    required this.len,
    required this.capacity,
  });

  @override
  int get hashCode => ptr.hashCode ^ len.hashCode ^ capacity.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SharedTensorBuffer &&
          runtimeType == other.runtimeType &&
          ptr == other.ptr &&
          len == other.len &&
          capacity == other.capacity;
}
