name: Build Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_android:
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          # Targets for standard Android architectures
          targets: aarch64-linux-android, armv7-linux-androideabi, x86_64-linux-android, i686-linux-android

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install flutter_rust_bridge_codegen
        run: cargo install flutter_rust_bridge_codegen --version ^2.0.0

      - name: Generate Rust Bindings
        working-directory: ./ui
        run: flutter_rust_bridge_codegen generate

      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Dependencies
        working-directory: ./ui
        run: flutter pub get

      - name: Build Android APK
        working-directory: ./ui
        run: flutter build apk --release

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Mesh-UI-Android-APK
          path: ui/build/app/outputs/flutter-apk/app-release.apk
